# This workflow has four tasks:
#
# 1. the first builds inspircd (with some optimizations for irctest), and uploads it
#    to a temporary storage
# 2. the other three download the binary we just built, and run it through inspircd,
#    with either Anope, Atheme, or runs service-independent tests

name: "irctest"

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip irctest ci]')"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Install dependencies"
        run: "sudo apt-get install -y libfmt-dev"  # required to precompile inspircd.h???

      - name: "Checkout irctest"
        uses: "actions/checkout@v3"
        with:
          path: irctest
          ref: 3b7f81e22c317eae885f5a942767ba4f6a30414e
          repository: progval/irctest

      # Speed-up the main loop
      # (for some reason, 'patch' claims the patch is reversed?????)
      #- name: "Apply irctest patches"
      #  run: "patch src/inspircd.cpp < irctest/patches/inspircd_mainloop.patch"

      - name: "Run configure"
        run: "./configure --development --disable-auto-extras --prefix=$HOME/.local/"

      # Speed-up build (6 min -> 5 min)
      - name: "Precompile inspircd.h"
        run: "g++ include/inspircd.h"

      - name: "Build and Install"
        run: "make install --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))"

      - name: Make artefact tarball
        run: cd ~; tar -czf artefacts-inspircd.tar.gz .local/

      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: installed-inspircd-for-irctest
          path: ~/artefacts-*.tar.gz
          retention-days: 1

  test:
    if: "!contains(github.event.head_commit.message, '[skip irctest ci]')"
    runs-on: "ubuntu-22.04"
    needs:
    - build
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v3
        with:
          name: installed-inspircd-for-irctest
          path: '~'

      - name: Unpack artefacts
        run: cd ~; find -name 'artefacts-*.tar.gz' -exec tar -xzf '{}' \;

      - name: "Checkout irctest"
        uses: "actions/checkout@v3"
        with:
          path: irctest
          ref: 3b7f81e22c317eae885f5a942767ba4f6a30414e
          repository: progval/irctest

      - name: "Install irctest dependencies"
        run: "sudo apt-get install -y python3-pytest python3-pytest-xdist"

      - name: "Install Atheme"
        run: "sudo apt-get install -y atheme-services"
        if: "matrix.services == 'atheme'"

      # Can't apt-get install Anope if we want Insp4 support
      - name: Checkout Anope
        uses: actions/checkout@v3
        with:
          path: anope
          ref: 2.0.9
          repository: anope/anope
        if: "matrix.services == 'anope'"
      - name: "Build and Install Anope"
        run: |
          cd $GITHUB_WORKSPACE/anope/
          cp $GITHUB_WORKSPACE/irctest/data/anope/* .
          CFLAGS=-O0 ./Config -quick
          make -C build --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))
          make -C build install
        if: "matrix.services == 'anope'"

      - name: "Run irctest (Atheme services)"
        run: "PATH=$HOME/.local/bin:$PATH make -C irctest/ inspircd-atheme PYTEST_ARGS='-n 4'"
        if: "matrix.services == 'atheme'"

      - name: "Run irctest (Anope services)"
        run: "PATH=$HOME/.local/bin:$PATH make -C irctest/ inspircd-anope PYTEST_ARGS='-n 4'"
        if: "matrix.services == 'anope'"

      - name: "Run irctest (no services)"
        run: "PATH=$HOME/.local/bin:$PATH make -C irctest/ inspircd PYTEST_ARGS='-n 4'"
        if: "matrix.services == 'no services'"

    strategy:
      fail-fast: false
      matrix:
        services:
          - no services
          - atheme  # Atheme works on Insp3, but not Insp4
          - anope
