name: "irctest"

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip irctest ci]')"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Checkout irctest"
        uses: "actions/checkout@v3"
        with:
          path: irctest
          ref: 3b7f81e22c317eae885f5a942767ba4f6a30414e
          repository: progval/irctest

      # Speed-up the main loop
      # (for some reason, 'patch' claims the patch is reversed?????)
      #- name: "Apply irctest patches"
      #  run: "patch src/inspircd.cpp < irctest/patches/inspircd_mainloop.patch"

      # Speed-up build by removing large modules that won't be used
      - name: "Remove unused modules"
        run: "rm -rf src/modules/m_spanningtree/"

      - name: "Run configure"
        run: "./configure --development --disable-auto-extras"

      # Speed-up build
      - name: "Precompile inspircd.h"
        run: "g++ include/inspircd.h"

      - name: "Build and Install"
        run: "make install --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))"

      - name: Make artefact tarball
        run: cd ~; tar -czf artefacts-inspircd.tar.gz .local/

      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: installed-inspircd-for-irctest
          path: ~/artefacts-*.tar.gz
          retention-days: 1

  test:
    if: "!contains(github.event.head_commit.message, '[skip irctest ci]')"
    runs-on: "ubuntu-22.04"
    needs:
    - build
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v3
        with:
          name: installed-inspircd-for-irctest
          path: '~'

      - name: "Checkout irctest"
        uses: "actions/checkout@v3"
        with:
          path: irctest
          ref: 3b7f81e22c317eae885f5a942767ba4f6a30414e
          repository: progval/irctest

      - name: "Install irctest dependencies"
        run: "sudo apt install -y python3-pytest python3-pytest-xdist"

      - name: "Install Atheme"
        run: "sudo apt install -y atheme-services"
        if: ${{ matrix.services }} == atheme

      - name: "Install Anope"
        run: "sudo apt install -y anope"
        if: ${{ matrix.services }} == anope

      - name: "Run irctest (Atheme services)"
        run: "make -C irctest/ inspircd PYTEST_ARGS='-n $(($(getconf _NPROCESSORS_ONLN) + 1))'"
        if: ${{ matrix.services }} == atheme

      - name: "Run irctest (Anope services)"
        run: "make -C irctest/ inspircd-anope PYTEST_ARGS='-n $(($(getconf _NPROCESSORS_ONLN) + 1))'"
        if: ${{ matrix.services }} == anope

      - name: "Run irctest (no services)"
        run: "make -C irctest/ inspircd-atheme PYTEST_ARGS='-n $(($(getconf _NPROCESSORS_ONLN) + 1))'"
        if: ${{ matrix.services }} == 'no services'

    strategy:
      fail-fast: false
      matrix:
        services:
          - no services
          - atheme
          - anope
